### ISSUE TITLE
support for https [enhancement]

### ISSUE THREAD

**Issue by epcim** [chef-cookbooks/subversion#14]
Any ideas? What way Apache cookbook support it?
I have local example w/o chef, but I would like to "copy&paste" from another app+apache cookbook reference implementation, instead of make it up own.

(+ similary the ldap auth)

**Comment by iennae** [comment]
@epcim 

It's been a while since anyone has responded to this, apologies for the delay. We're definitely open to pull requests, but the cookbook works as is for its implementation. We'd love to have an https enhancement, but it's not something we have the bandwidth to add to this cookbook.
