### ISSUE TITLE
Depends on apache ~> 2

### ISSUE THREAD

**Issue by EasyAsABC123** [chef-cookbooks/subversion#15]
Apache is now past version 3.0.1, it also is only needed for server installation not client.

Any solutions?

**Comment by michael-misshore** [comment]
@EasyAsABC123, I just submitted a pull request for it here: https://github.com/opscode-cookbooks/subversion/pull/18

Likewise, you can use our fork in the meantime: https://github.com/mudbugmedia/subversion

Let me know if you encounter any issues.

**Comment by EasyAsABC123** [comment]
@michael-misshore this is definitely progress however, apache is technically an optional depends not a depends...this is a difficult problem, but hopefully someone comes with some idea.

**Comment by michael-misshore** [comment]
@EasyAsABC12, Maybe the "depends" could be converted to use "recommends" or "suggests"? I'm more inclined to pick "recommends" between the two, as the apache2 cookbook is more than "informational only." However, this still feels weird as a recipe specifically depends on that cookbook. Tough call...

**Comment by tas50** [comment]
The depends has been updated to allow for the latest version.  I'll get a new release pushed to Supermarket next week
