### ISSUE TITLE
subversion windows_path does not work as expected

### ISSUE THREAD

**Issue by puneetloya** [chef-cookbooks/subversion#19]
In the same chef shell session I am installing subversion on windows and using it for checking out code.
The windows_path has the subversion path is added by default, but on checking out code using subversion resource says "svn: No such file or Directory"

**Comment by gh2k** [comment]
I'm having the same problem. Output from converge:
```
       Recipe: subversion::client
       
         Recipe: <Dynamically Defined Resource>
       
             - create new file C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/Setup-Subversion-1.7.0.msi
             - update content in file C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/Setup-Subversion-1.7.0.msi from none to 2ee93a
             (new content is binary, diff output suppressed)
         
       Recipe: subversion::client
         * windows_path[C:\Program Files (x86)\Subversion\bin] action add
        (up to date)
           * ruby_block[fix ruby ENV['PATH']] action nothing (skipped due to action :nothing)
            (up to date)
```

After logging into the affected host, 'svn' is in the PATH... I suspect that for the current chef run it isn't in there as the process was started before PATH was modified. That ```ruby_block[fix ruby ENV['PATH']] action nothing``` looks like it might be a culprit?

**Comment by gh2k** [comment]
It looks like this could be related to opscode-cookbooks/windows#111

**Comment by tas50** [comment]
This is fixed on master
