### ISSUE TITLE
Pessimistic version on windows cookbook dependency causing resolution issues 

### ISSUE THREAD

**Issue by ryangribble** [chef-cookbooks/subversion#23]
### Cookbook version
2.1

### Chef-client version
12.15.19

### Platform Details
OSX Siera

### Scenario:
The [dependency on windows cookbook](https://github.com/chef-cookbooks/subversion/blob/master/metadata.rb#L14) `depends 'windows', '~> 1.44'` is preventing dependency resolution when used in a runlist with other cookbooks that require `'windows', '>=2.0'`

### Steps to Reproduce:
Add a berks reference to this cookbook, as well as `'windows', '>=2.0'`

### Expected Result:
Unless there is a specific reason causing this cookbook to not work with `windows` cookbook after 1.44.x, the dependency specified in this cookbook should be `'>= 1.44'` to allow greater operability with other cookbooks that may require a later `windows` cookbook version

### Actual Result:
Berkshelf is unable to solve the dependencies due to `'~>1.44'` not working with `'>=2.0'`

**Comment by tas50** [comment]
Fixed in 2.1.1

**Comment by ryangribble** [comment]
Many thanks! 🎉
