### ISSUE TITLE
subversion::server converges execute[create htpasswd file] on every run

### ISSUE THREAD

**Issue by sunruh** [chef-cookbooks/subversion#9]
The reason for this is a wrong value for the `creates` attribute on the `execute[create htpasswd file]` resource.

It should read `creates "#{node['subversion']['repo_dir']}/htpasswd"` correctly.

**Comment by sunruh** [comment]
Fixed by #10

**Comment by epcim** [comment]
Well you are right, I was not aware of that. On the other hand there may be need to update "subversion" password each time - so it match one in case it's later updated in node attributes. 

So I vote for to merge also the second part from mine #11

```ruby
execute 'update htpasswd file' do
      command "htpasswd -sb #{node['subversion']['repo_dir']}/htpasswd #{node['subversion']['user']}      #{node['subversion']['password']}"
end
```

**Comment by sunruh** [comment]
You might want to take a look at the [htpasswd](https://supermarket.chef.io/cookbooks/htpasswd) cookbook.

If you remove the `creates` attribute from the execute resource, it will execute on every chef run, even if the password does not change, which contradicts the idempotence paradigm of chef.

**Comment by tas50** [comment]
This should be fixed on master now
